// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5176.RoboCode421Ez.commands;

import org.usfirst.frc.team5176.RoboCode421Ez.subsystems.*;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousCommandGroup extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutonomousCommandGroup() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
     
    	
    	
    	
    	/*  addSequential(new DriveToBall());
       // addSequential(new PickupBall()); Rather, spin in --> raise --> spin out
        addSequential(new DriveToDefense()); 
        addSequential(new DriveOverDefense());
        addSequential(new LineUpShot());
        addSequential(new ShootBallPID());
        addSequential(new ReturntoNeutralZone());
		*/
    	
    	
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	
    	//This is the test autonomous command just to make sure that this bullshit works gooood
    	
    	 //Changed for test so it's a simple drive forward
    	//Just cause I'm too lazy to make a new one
    	addSequential(new DriveToDefense());  //Changed for test so it's a simple drive backward
    	addParallel(new SpinPickupArmsIn());
    	addSequential(new LowerPickupArms());
    	addParallel(new SpinPickupArmsIn());
    	addSequential(new RaisePickupArms());
    	addSequential(new SpinPickupArmsIn());
    	addSequential(new TurnLeft());
    	addSequential(new DriveToBall());
    	addSequential(new Firrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrre());
    	
 
    } 
}
