// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5176.RoboCode421Ez.subsystems;

import org.usfirst.frc.team5176.RoboCode421Ez.RobotMap;
import org.usfirst.frc.team5176.RoboCode421Ez.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController frontLeftMotor = RobotMap.driveTrainFrontLeftMotor;
    private final SpeedController rearLeftMotor = RobotMap.driveTrainRearLeftMotor;
    private final SpeedController frontRightMotor = RobotMap.driveTrainFrontRightMotor;
    private final SpeedController rearRightMotor = RobotMap.driveTrainRearRightMotor;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    private final Ultrasonic ultrasonic = RobotMap.driveTrainUltrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ArcadeDrive());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void dankMemes(Joystick stick)
    {
    	robotDrive.arcadeDrive(stick);
    }
    public void set(double fl, double rl, double fr, double rr)
    {
    	frontLeftMotor.set(fl);
    	rearLeftMotor.set(rl);
    	frontRightMotor.set(fr);
    	rearRightMotor.set(rr);
    }
    public void freakingFloorIt()
    {
    	this.set(1, 1, 1, 1);
    }
    public void stopMoving()
    {
    	this.set(0, 0, 0, 0);
    }
    public void driveSlowly()
    {
    	this.set(.5, .5, .5, .5);
    }
}

